### ISSUE TITLE
Include tests in sdist

### ISSUE THREAD

**Issue by jayvdb** [TriOptima/tri.struct#3]
Please add tests to the sdist uploaded to PyPI, so that they can be used to verify the built library.

Using `check-manifest` from PyPI is a great automate-able way to ensure that all necessary artifacts are included in `MANIFEST.in`.

This only affects the sdist; it will not increase the download size of the wheels. c.f. https://github.com/TriOptima/tri.struct/issues/2

In any case, the size of the tests here is negligible.

**Comment by boxed** [comment]
I don't agree. Running tests is too big of a thing.
